script fix error handling

diff --git a/roles/setup_kea_dhcp4_server/templates/libdhcp_run_script.sh.j2 b/roles/setup_kea_dhcp4_server/templates/libdhcp_run_script.sh.j2
--- a/roles/setup_kea_dhcp4_server/templates/libdhcp_run_script.sh.j2
+++ b/roles/setup_kea_dhcp4_server/templates/libdhcp_run_script.sh.j2
@@ -19,7 +19,8 @@ if [ -n "$1" ] && [ -n "${HNAME}" ] && [ -n "${LEASE_ADDRESS}" ]; then
             ACTION=ADD
         ;;
         *)
-            echo "Error: invalid action \"ACTION\"."  exit 3
+            echo "Error: invalid action ${1} for ${HNAME} (${LEASE_ADDRESS}). Skip."
+            exit 3
         ;;
     esac
 
